### ISSUE TITLE
Why allowing magic numbers?

### ISSUE THREAD

**Issue by yannicklamprecht** [Chazmondo/AdvancementAPI#12]
Why using a String to create a frame type?
Why not using .frame(FrameType.RANDOM()) instead to get a random FrameType?!

https://github.com/Chazmondo/AdvancementAPI/blob/master/AdvancementAPI.java#L156-L165

**Comment by JarvisCraft** [comment]
This was made as a way to let developers easier integrate String input from their configs

**Comment by yannicklamprecht** [comment]
Ok I’ll readd it into FrameType. 

FrameType.getFromString(String frameType )

**Comment by JarvisCraft** [comment]
I think that it should be closed now
