### ISSUE TITLE
Overhaul the Conditions

### ISSUE THREAD

**Issue by yannicklamprecht** [Chazmondo/AdvancementAPI#16]
We need to create a Condition for each available Condition in documentation

https://github.com/Chazmondo/AdvancementAPI/pull/15#discussion_r123210578

**Comment by Ry-DS** [comment]
I did that for triggers in my pull request. It would be painful to make it for conditions

**Comment by yannicklamprecht** [comment]
I didn’t find the pull request. Can you send me the link?
Edit: Found it „revamped trigger“

Edit2: though of adding a builder class foreach trigertype.
I have to evaluate my idea.
Can be working and will make it easy adapting trigger changes.

**Comment by ysl3000** [comment]
Found it „revamped trigger“
