### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by Rocologo** [Chazmondo/AdvancementAPI#19]
I would be nice have an updated example in the wiki. Im not familar with how to use Advancements and and how the json file/files should look like when my code is okay

**Comment by SamB440** [comment]
Couldn't agree more.. even Chazmondo doesn't know how to use it..

**Comment by Skill** [comment]
I did state this earlier, everybody suddenly made this really complex which I really don't like.. if someone can edit the wiki page (by signing up and clicking edit) and adding some examples it would be good.

**Comment by yannicklamprecht** [comment]
https://pluginwiki.io/advancementapi?do=revisions

Hope that helps now.

**Comment by Rocologo** [comment]
Yes, the example is very nice now! Thank you. It clarifies how to make the parent and child. Thanks alot!

But I just tried the newest AdvancementAPI (https://github.com/Chazmondo/AdvancementAPI/blob/master/src/main/java/io/chazza/advancementapi/AdvancementAPI.java) and it cant compile now??? After this lombok was added??? 

I get an error in line 60 :
Trigger.TriggerBuilder cannot be resolved to a type

**Comment by yannicklamprecht** [comment]
Did you compile it with maven and added the Lombok dependency to your pom.xml ?

**Comment by yannicklamprecht** [comment]
I think we’ll have to Delombok everything or find a solution to make a difference between development version and delomboked usable version.

**Comment by Skill** [comment]
Yeah I couldn't import this myself with IntelliJ version control, would be nice if someone could make the code more straight forward, even if it means multiple classes.

**Comment by Rocologo** [comment]
Yes I added lombok to my pom.xml file. Thats not the problem

**Comment by yannicklamprecht** [comment]
Should I separate  the classes and Delombok all? 
Give. Me time to walk home and you’ll get it in time.

**Comment by yannicklamprecht** [comment]
#20 here you are. 👍

**Comment by Rocologo** [comment]
Thank you for the Delombok, it makes the code alot clearer to me! 

The AdvancementAPI.java, Condition.java, Trigger.java, FrameType.java all compiles fine now! I stongly recommed @Chazmondo to accept your pull.

The AdvancementAPITest.java could not compile because of the Mockito stuff. 

    @Before
    public void setUp() {
        World world = mock(World.class);


        Mockito.when(world.getWorldFolder()).thenReturn(worldFile);

        Server server = mock(Server.class);
        Mockito.when(server.getLogger()).thenReturn(Logger.getAnonymousLogger());
        Mockito.when(server.getWorld("world")).thenReturn(world);
        Mockito.when(server.getVersion()).thenReturn("AdvancementTestMocking");
        Mockito.when(server.getVersion()).thenReturn("AdvancementTestMocking");
        Bukkit.setServer(server);
    }

The "import org.mockito.Mockito;" does not work. 

Anyway. Thank you for your help, I dont need the Test file, and so I will try to implement the API now.

**Comment by yannicklamprecht** [comment]
@Rocologo I think you’re both making something wrong. Did you add framework support (maven) to allow compiling with the dependencies. Is maven new for you?

**Comment by Rocologo** [comment]
I am still having problems. 

I have tried using the code createAndSave(String worldName) from your AdvancementsAPITTest.java without any changes. When my server starts two files (addiction.json+firststeps.json) is created in the directory ./world/test/my/* , so this part looks fine. I get no errors in the console.

BUT when i join the server and and look at the Advancements, there is not created any tabs with the parent advancement added????

Either I do something wrong or your example does not work?

**Comment by yannicklamprecht** [comment]
You have to grant it. 
/advancement grant playername only test:my/firststeps 


And use the add() method when on spigotserver.

**Comment by Rocologo** [comment]
Maven is not completely new to me, but okay I'm properly a master yet :-) I cant see any dependency or repository for the Mockito ? 

I have tried granting when I join the server but I get an error.

I added the two advancements to an ArrayList (apiList) and run  this method onPlayerJoins()

public void updatePlayerAdvancements(Player player) {
		for (AdvancementAPI api : apiList) {
			if (api.getDescription().getText().equalsIgnoreCase("Starting")) {
				Messages.debug("Granting %s", api.getDescription().getText());
				api.grant(player);
			} else {
				Messages.debug("Not granting %s", api.getDescription().getText());
			}
		}
}

[11:07:36 WARN]: [MobHunting] Task #1362 for MobHunting v5.0.0-SNAPSHOT-Blocal generated an exception
java.lang.IllegalArgumentException: advancement
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.getAdvancementProgress(CraftPlayer.java:1449) ~[spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at io.chazza.advancementapi.AdvancementAPI.grant(AdvancementAPI.java:192) ~[?:?]
	at io.chazza.advancementapi.AdvancementManager.updatePlayerAdvancements(AdvancementManager.java:124) ~[?:?]
	at one.lindegaard.MobHunting.achievements.AchievementManager$3.onCompleted(AchievementManager.java:621) ~[?:?]
	at one.lindegaard.MobHunting.achievements.AchievementManager$3.onCompleted(AchievementManager.java:560) ~[?:?]
	at one.lindegaard.MobHunting.storage.DataStoreManager$CallbackCaller.run(DataStoreManager.java:324) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by Rocologo** [comment]
About Maven: you write "Did you add framework support (maven)" maybe this is where i misunderstand something? Add framework? I looked for dependencies in the pom.xml in your code, but I could not find any? How do I add framework support?  

I dont think this is very important, because I can compile your code now, I just removed setup(). which I of cause dont need in my own plugin

**Comment by yannicklamprecht** [comment]
A Unit test is only for testing if an unit is working welll. The real example is at the wiki.

By the way which IDE you’re using? IntelliJ idea?

https://dukescript.com/assets/duke-8.png
On the right side you’ll find the maven window. There you see a lifecycle. Install is used once to load all dependencies. The tasks from clean to verify should be executed when you want to build your project. Select it and use the play button in this window. Never press the play button on the main bar.

**Comment by yannicklamprecht** [comment]
Here I'll have to take the screenshot myself -> image will get removed in future and my own get added. (legal concerns)

![duke-8](https://user-images.githubusercontent.com/1420893/27515284-0085ffba-59a0-11e7-982c-e9756c0397b4.png)

**Comment by Rocologo** [comment]
I have used Eclipse for years now. I have never made unit testing. I guess I have never spend time finding  a guide. Maybe this is the time :-) 

I still dont understand this: will the test unit find "org.mockito.Mockito" because this is the problem. I have no repository for this dependency.

**Comment by yannicklamprecht** [comment]
I don't know how Eclipse is handling Maven projects. The last time I used Eclipse is 3-4 year ago.
At this time I didn't use Maven and one problem was that the git (egit) support wasn't good.
Now I'm addicted to Jetbrains products.


Edit:
By the way I looked into your MobHunting project. You're misusing the maven structure. It's like eye cancer for me. Non Maven dependencies can be installed locally or on your own maven repository. Mockito, JUnit and Lombok didn't work when not adding it to pom.xml.  Cleaning up your project will allow a better handling.

**Comment by Rocologo** [comment]
He he, Im not misusing the structure, I am using it as my knowledge allows :-)  as I said: "Im not a master" If you give an example on where use the structure the wrong way, and help me how to do it the right way, I will clean up the pom.xml 

Granting does still not work, I get the error above, no matter what I try?

**Comment by Rocologo** [comment]
PS. I added the Lombok repository to my pom.xml, but I removed it too, like you did. I have not seen an Mockito dependency, but test is added to the pom.xml on eclipse, i have just not pushed my new pom to github yet. 

			<dependency>
				<groupId>org.testng</groupId>
				<artifactId>testng</artifactId>
				<scope>test</scope>
				<version>6.8.8</version>
			</dependency>

**Comment by yannicklamprecht** [comment]
https://github.com/Chazmondo/AdvancementAPI/blob/master/pom.xml#L20-L25

This is the mockito dependency.


OFF TOPIC:
Install your local dependencies to a maven repository.
Here is a tutorial: https://www.jfrog.com/confluence/display/RTF/Deploying+Artifacts
 It'll minimize your project size.
I think that this https://github.com/Rocologo/MobHunting/blob/master/pom.xml#L787-L798  can be used as a maven repository for your files. Here is the web panel https://fractal.lindegaard.one:8187/artifactory/webapp/#/home

https://github.com/Rocologo/MobHunting/blob/master/pom.xml#L466-L662
https://github.com/Rocologo/MobHunting/blob/master/pom.xml#L691-L722
https://github.com/Rocologo/MobHunting/blob/master/pom.xml#L732-L757

Why not using the Logger available in Bukkit?
https://github.com/Rocologo/MobHunting/blob/master/pom.xml#L765-L781

**Comment by Rocologo** [comment]
Yes, definitely OFF TOPIC, we should continue this discussion here https://github.com/Rocologo/MobHunting/issues/262

**Comment by Rocologo** [comment]
There is no other reason for using "org.slf4j..slf4j-api" than this is something i which was made by the previous developer, when I toke over this project 2½ year ago. I agree I should change this to Bukkits Logger....  I will create a ticket to myself on this topic.

**Comment by Skill** [comment]
As discussed somewhere, closing.
