### ISSUE TITLE
Rewards?

### ISSUE THREAD

**Issue by 501warhead** [Chazmondo/AdvancementAPI#22]
Hey!

I just wanted to drop by and say this thing looks fantastic so far. I've really got a lot of ideas and this API seems absolutely fantastic for what it does but I do have to ask! I don't see any API for the rewards of advancements, such as dungeon loot, recipe strings, etc. ([Wiki Page](http://minecraft.gamepedia.com/Advancements#JSON_Format))

I'd love to see these added and it's pretty much the only stopping point for me right now in utilizing it. Are there plans to add these in the near future?

Thanks for all the work you've done! Again, this API looks really good!

**Comment by Jamie4224** [comment]
Use this event instead:
org.bukkit.event.player.PlayerAdvancementDoneEvent

**Comment by 501warhead** [comment]
This works for firing code but as of this time bukkit does not support unlocking recipes @Jamie4224 

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/ShapedRecipe.html
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/ShapelessRecipe.html
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/FurnaceRecipe.html

Also checked Player as well. Pretty much there is no way in the Bukkit API yet to "unlock" crafting recipes for the player yet.
